# Generated by Django 5.2.13 on 2026-05-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("USER", "User")],
                default="USER",
                max_length=20,
            ),
        ),
    ]
