# Generated by Django 5.2.13 on 2026-05-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("sku",),
                name="unique_active_sku",
            ),
        ),
    ]
