# Generated by Django 5.2.13 on 2026-05-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_sku"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("category_name",),
                name="unique_category_name",
            ),
        ),
    ]
